//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBot.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZzukBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] beep {
            get {
                object obj = ResourceManager.GetObject("beep", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VBBDa2wO42o+a/KBAca+XQ== ähnelt.
        /// </summary>
        internal static string FasmNetMd5 {
            get {
                return ResourceManager.GetString("FasmNetMd5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] FastCallDll {
            get {
                object obj = ResourceManager.GetObject("FastCallDll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot set user mode for &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string MessageCannotSetUserMode {
            get {
                return ResourceManager.GetString("MessageCannotSetUserMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The channel type &apos;{0}&apos; sent by the server is invalid. ähnelt.
        /// </summary>
        internal static string MessageInvalidChannelType {
            get {
                return ResourceManager.GetString("MessageInvalidChannelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The message command &apos;{0}&apos; is invalid. ähnelt.
        /// </summary>
        internal static string MessageInvalidCommand {
            get {
                return ResourceManager.GetString("MessageInvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The command definition &apos;{0}&apos; is invalid. ähnelt.
        /// </summary>
        internal static string MessageInvalidCommandDefinition {
            get {
                return ResourceManager.GetString("MessageInvalidCommandDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The command &apos;{0}&apos; was not recognised. ähnelt.
        /// </summary>
        internal static string MessageInvalidMessageCommand {
            get {
                return ResourceManager.GetString("MessageInvalidMessageCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The non-trailing parameter &apos;{0}&apos; is invalid. ähnelt.
        /// </summary>
        internal static string MessageInvalidMiddleParameter {
            get {
                return ResourceManager.GetString("MessageInvalidMiddleParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified nick name is invalid. ähnelt.
        /// </summary>
        internal static string MessageInvalidNickName {
            get {
                return ResourceManager.GetString("MessageInvalidNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified password is invalid. ähnelt.
        /// </summary>
        internal static string MessageInvalidPassword {
            get {
                return ResourceManager.GetString("MessageInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The message prefix &apos;{0}&apos; is invalid. ähnelt.
        /// </summary>
        internal static string MessageInvalidPrefix {
            get {
                return ResourceManager.GetString("MessageInvalidPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The quoted character &apos;{0}&apos; was not recognised. ähnelt.
        /// </summary>
        internal static string MessageInvalidQuotedChar {
            get {
                return ResourceManager.GetString("MessageInvalidQuotedChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified real name is invalid. ähnelt.
        /// </summary>
        internal static string MessageInvalidRealName {
            get {
                return ResourceManager.GetString("MessageInvalidRealName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The object provided for registration info is of an unknown type. ähnelt.
        /// </summary>
        internal static string MessageInvalidRegistrationInfoObject {
            get {
                return ResourceManager.GetString("MessageInvalidRegistrationInfoObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The registration info for a service must have a valid nick name and description. ähnelt.
        /// </summary>
        internal static string MessageInvalidServiceRegistrationInfo {
            get {
                return ResourceManager.GetString("MessageInvalidServiceRegistrationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The source &apos;{0}&apos; of the message was not recognised as either a server or user. ähnelt.
        /// </summary>
        internal static string MessageInvalidSource {
            get {
                return ResourceManager.GetString("MessageInvalidSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The message tag &apos;{0}&apos; is invalid. ähnelt.
        /// </summary>
        internal static string MessageInvalidTag {
            get {
                return ResourceManager.GetString("MessageInvalidTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A target name may not contain any &apos;,&apos; character. ähnelt.
        /// </summary>
        internal static string MessageInvalidTargetName {
            get {
                return ResourceManager.GetString("MessageInvalidTargetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The trailing parameter &apos;{0}&apos; is invalid. ähnelt.
        /// </summary>
        internal static string MessageInvalidTrailingParameter {
            get {
                return ResourceManager.GetString("MessageInvalidTrailingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The URL scheme &apos;{0}&apos; is not valid. ähnelt.
        /// </summary>
        internal static string MessageInvalidUrlScheme {
            get {
                return ResourceManager.GetString("MessageInvalidUrlScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified user mode is invalid. ähnelt.
        /// </summary>
        internal static string MessageInvalidUserMode {
            get {
                return ResourceManager.GetString("MessageInvalidUserMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified user name is invalid. ähnelt.
        /// </summary>
        internal static string MessageInvalidUserName {
            get {
                return ResourceManager.GetString("MessageInvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The registration info for a user must have a valid nick name and user name. ähnelt.
        /// </summary>
        internal static string MessageInvalidUserRegistrationInfo {
            get {
                return ResourceManager.GetString("MessageInvalidUserRegistrationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The ISUPPORT message sent by the server contains an invalid PREFIX parameter. ähnelt.
        /// </summary>
        internal static string MessageISupportPrefixInvalid {
            get {
                return ResourceManager.GetString("MessageISupportPrefixInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not enough mode parameters were specified for the given modes. ähnelt.
        /// </summary>
        internal static string MessageNotEnoughModeParameters {
            get {
                return ResourceManager.GetString("MessageNotEnoughModeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The host name &apos;{0}&apos; does not resolve to a valid IP address. ähnelt.
        /// </summary>
        internal static string MessageNoValidAddress {
            get {
                return ResourceManager.GetString("MessageNoValidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The length of a raw message must not exceed {0} characters. ähnelt.
        /// </summary>
        internal static string MessageRawMessageTooLong {
            get {
                return ResourceManager.GetString("MessageRawMessageTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The message source &apos;{0}&apos; is not a user. ähnelt.
        /// </summary>
        internal static string MessageSourceNotUser {
            get {
                return ResourceManager.GetString("MessageSourceNotUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The type of the given target mask &apos;{0}&apos; is invalid. ähnelt.
        /// </summary>
        internal static string MessageTargetMaskInvalidType {
            get {
                return ResourceManager.GetString("MessageTargetMaskInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The target mask must be contain at least two characters. ähnelt.
        /// </summary>
        internal static string MessageTargetMaskTooShort {
            get {
                return ResourceManager.GetString("MessageTargetMaskTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No more than 3 mode parameters may be sent per message. ähnelt.
        /// </summary>
        internal static string MessageTooManyModeParameters {
            get {
                return ResourceManager.GetString("MessageTooManyModeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No more than 15 command parameters may be specified. ähnelt.
        /// </summary>
        internal static string MessageTooManyParams {
            get {
                return ResourceManager.GetString("MessageTooManyParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The value cannot be an empty string ähnelt.
        /// </summary>
        internal static string MessageValueCannotBeEmptyString {
            get {
                return ResourceManager.GetString("MessageValueCannotBeEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die wow.exe
        ///ntdll.dll
        ///kernel32.dll
        ///kernelbase.dll
        ///advapi32.dll
        ///msvcrt.dll
        ///sechost.dll
        ///rpcrt4.dll
        ///sspicli.dll
        ///cryptbase.dll
        ///comctl32.dll
        ///gdi32.dll
        ///user32.dll
        ///lpk.dll
        ///usp10.dll
        ///shell32.dll
        ///shlwapi.dll
        ///wsock32.dll
        ///ws2_32.dll
        ///nsi.dll
        ///opengl32.dll
        ///glu32.dll
        ///ddraw.dll
        ///dciman32.dll
        ///setupapi.dll
        ///cfgmgr32.dll
        ///oleaut32.dll
        ///ole32.dll
        ///devobj.dll
        ///dwmapi.dll
        ///imm32.dll
        ///msctf.dll
        ///divxdecoder.dll
        ///winmm.dll
        ///fmod.dll
        ///msacm32.dll
        ///wininet.dll
        ///api-ms-win-downlevel-user32-l1-1-0.dll
        ///api-ms-win-do [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ModulesOfWoW {
            get {
                return ResourceManager.GetString("ModulesOfWoW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Navigation {
            get {
                object obj = ResourceManager.GetObject("Navigation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zb {
            get {
                object obj = ResourceManager.GetObject("zb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
